server:
  port: 2333

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.16.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.0"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      local: true
      http: true

lavasrc:
  sources:
    spotify: true
  spotify:
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}
